package views;

import com.fasterxml.jackson.databind.node.ObjectNode;
import forms.SearchForm;
import models.FinancialPerformance;
import models.MovieOrTVShow;
import models.PersonStats;
import models.Readability;
import models.Review;
import models.ReviewsSummary;
import org.junit.Before;
import org.junit.Test;
import org.webjars.play.WebJarsUtil;
import play.data.Form;
import play.data.FormFactory;
import play.i18n.Messages;
import play.i18n.MessagesApi;
import play.libs.Json;
import play.mvc.Http;
import play.test.Helpers;
import play.test.WithApplication;

import java.io.ByteArrayOutputStream;
import java.io.ObjectOutputStream;
import java.util.Arrays;
import java.util.Collections;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

/**
 * Coverage-oriented tests for Twirl templates under views.html.
 *
 * These tests explicitly exercise helper methods generated by Twirl objects
 * (render/f/ref/writeReplace/default args) and hit uncovered conditional paths
 * inside templates to complete JaCoCo coverage for views.html.
 *
 * @author Syed Shahab Shah
 */
public class ViewsTemplateCoverageTest extends WithApplication {

    private Http.Request request;
    private Messages messages;
    private Form<SearchForm> searchForm;
    private WebJarsUtil webJarsUtil;

    @Before
    public void setUp() {
        request = Helpers.fakeRequest().build();
        messages = app.injector().instanceOf(MessagesApi.class).preferred(request);
        searchForm = app.injector().instanceOf(FormFactory.class).form(SearchForm.class);
        webJarsUtil = app.injector().instanceOf(org.webjars.play.WebJarsUtil.class);
    }

    @Test
    public void testIndexTemplateBranchesAndObjectHelpers() throws Exception {
        // Cover resultsJson short-circuit branches: null, empty, non-empty
        String nullHtml = views.html.index.render(searchForm, request, messages, null, webJarsUtil).body();
        assertTrue(nullHtml.contains("Welcome to FlickLytics"));

        String emptyHtml = views.html.index.render(searchForm, request, messages, "", webJarsUtil).body();
        assertTrue(emptyHtml.contains("Welcome to FlickLytics"));

        String resultsJson = "["
                + "{\"query\":\"tom\",\"category\":\"person\",\"total_results\":1,"
                + "\"results\":[{\"id\":31,\"name\":\"Tom Hanks\",\"popularity\":10.1,\"gender\":2,\"known_for_department\":\"Acting\",\"photo_link\":\"https://img\"}]},"
                + "{\"query\":\"dark\",\"category\":\"movie\",\"total_results\":1,"
                + "\"results\":[{\"id\":1,\"title\":\"Dark\",\"link\":\"/movie/1\",\"language\":\"en\",\"genres\":[\"Drama\"],\"release_date\":\"2020-01-01\",\"popularity\":2.2,\"vote_average\":8.0}]}"
                + "]";
        String populatedHtml = views.html.index.render(searchForm, request, messages, resultsJson, webJarsUtil).body();
        assertTrue(populatedHtml.contains("Known for"));
        assertTrue(populatedHtml.contains("Financial Performance"));

        // Cover object helper methods that JaCoCo tracks separately
        assertNotNull(views.html.index$.MODULE$.f());
        assertEquals(views.html.index$.MODULE$, views.html.index$.MODULE$.ref());
        assertEquals(null, views.html.index$.MODULE$.apply$default$4(searchForm));
        assertSerialized(views.html.index$.MODULE$);
    }

    @Test
    public void testDetailsTemplateBranchesAndObjectHelpers() throws Exception {
        Readability.ReadabilityScores scores = new Readability.ReadabilityScores(65.0, 8.0, 10, 200, 300);

        // Movie true branches
        ObjectNode movieTrue = Json.newObject();
        movieTrue.put("poster_path", "/poster.jpg");
        movieTrue.put("homepage", "https://movie.example");
        movieTrue.set("genres", Json.newArray().add(Json.newObject().put("name", "Action")));
        movieTrue.set("production_companies", Json.newArray().add(Json.newObject().put("name", "Studio A")));
        String movieHtmlTrue = views.html.details.render("movie", movieTrue, "Movie overview", scores, request, messages, webJarsUtil).body();
        assertTrue(movieHtmlTrue.contains("Movie Details"));
        assertTrue(movieHtmlTrue.contains("Studio A"));

        // Movie false branches
        ObjectNode movieFalse = Json.newObject();
        movieFalse.put("poster_path", "");
        movieFalse.put("homepage", "");
        movieFalse.put("genres", "not-array");
        movieFalse.put("production_companies", "not-array");
        String movieHtmlFalse = views.html.details.render("movie", movieFalse, "Movie overview", scores, request, messages, webJarsUtil).body();
        assertTrue(movieHtmlFalse.contains("N/A"));

        // TV true branches
        ObjectNode tvTrue = Json.newObject();
        tvTrue.put("poster_path", "/tv.jpg");
        tvTrue.put("homepage", "https://tv.example");
        tvTrue.set("genres", Json.newArray().add(Json.newObject().put("name", "Drama")));
        tvTrue.set("networks", Json.newArray().add(Json.newObject().put("name", "HBO")));
        String tvHtmlTrue = views.html.details.render("tv", tvTrue, "TV overview", scores, request, messages, webJarsUtil).body();
        assertTrue(tvHtmlTrue.contains("TV Show Details"));
        assertTrue(tvHtmlTrue.contains("HBO"));

        // TV false branches
        ObjectNode tvFalse = Json.newObject();
        tvFalse.put("poster_path", "");
        tvFalse.put("homepage", "");
        tvFalse.put("genres", "not-array");
        tvFalse.put("networks", "not-array");
        String tvHtmlFalse = views.html.details.render("tv", tvFalse, "TV overview", scores, request, messages, webJarsUtil).body();
        assertTrue(tvHtmlFalse.contains("N/A"));

        // Null itemType path covers remaining Scala equality branches for itemType checks
        String nullTypeHtml = views.html.details.render(null, Json.newObject(), "Overview", scores, request, messages, webJarsUtil).body();
        assertTrue(nullTypeHtml.contains("TV Show Details"));

        // Non-matching non-null itemType covers the last comparison branch
        String otherTypeHtml = views.html.details.render("documentary", Json.newObject(), "Overview", scores, request, messages, webJarsUtil).body();
        assertTrue(otherTypeHtml.contains("TV Show Details"));

        // Non-interned strings exercise additional Scala equality bytecode paths
        String nonInternMovie = new String("movie");
        String nonInternTv = new String("tv");
        String movieNonInternHtml = views.html.details.render(nonInternMovie, movieTrue, "Movie overview", scores, request, messages, webJarsUtil).body();
        String tvNonInternHtml = views.html.details.render(nonInternTv, tvTrue, "TV overview", scores, request, messages, webJarsUtil).body();
        assertTrue(movieNonInternHtml.contains("Movie Details"));
        assertTrue(tvNonInternHtml.contains("TV Show Details"));

        assertNotNull(views.html.details$.MODULE$.f());
        assertEquals(views.html.details$.MODULE$, views.html.details$.MODULE$.ref());
        assertSerialized(views.html.details$.MODULE$);
    }

    @Test
    public void testPersonStatsTemplateBranchesAndObjectHelpers() throws Exception {
        // Person name null branch
        PersonStats statsMissing = new PersonStats(Collections.singletonList(
                new MovieOrTVShow("1", "NoYear", 1.0, 2.0, 3, "")
        ));
        String missingHtml = views.html.personStats.render(statsMissing, request, messages, webJarsUtil).body();
        assertTrue(missingHtml.contains("Person Statistics"));

        // Age N/A and profile placeholder branch
        PersonStats statsAgeNa = new PersonStats(Collections.singletonList(
                new MovieOrTVShow("3", "AgeUnknown", 1.2, 2.2, 5, "")
        ));
        statsAgeNa.setPersonDetails("Unknown Age", "", "Acting", 2, "", "");
        String ageNaHtml = views.html.personStats.render(statsAgeNa, request, messages, webJarsUtil).body();
        assertTrue(ageNaHtml.contains("N/A"));
        assertTrue(ageNaHtml.contains("person-photo-placeholder"));

        // Profile photo shown + age years + year shown
        PersonStats statsFull = new PersonStats(Collections.singletonList(
                new MovieOrTVShow("2", "WithYear", 2.0, 3.0, 4, "2024")
        ));
        statsFull.setPersonDetails("Test Person", "/photo.jpg", "Acting", 2, "1990-01-01", "Somewhere");
        String fullHtml = views.html.personStats.render(statsFull, request, messages, webJarsUtil).body();
        assertTrue(fullHtml.contains("Test Person"));
        assertTrue(fullHtml.contains("photo.jpg"));
        assertTrue(fullHtml.contains("(2024)"));

        assertNotNull(views.html.personStats$.MODULE$.f());
        assertEquals(views.html.personStats$.MODULE$, views.html.personStats$.MODULE$.ref());
        assertSerialized(views.html.personStats$.MODULE$);
    }

    @Test
    public void testReviewsTemplateObjectHelpers() throws Exception {
        ReviewsSummary summary = new ReviewsSummary(Arrays.asList(
                new Review("A", "Great", ":-)", 100.0, 0.0),
                new Review("B", "Bad", ":-(", 0.0, 100.0),
                new Review("C", "Okay", ":-|", 0.0, 0.0)
        ));
        String html = views.html.reviews.render("movie", 1L, summary, request, messages, webJarsUtil).body();
        assertTrue(html.contains("Individual Reviews"));

        assertNotNull(views.html.reviews$.MODULE$.f());
        assertEquals(views.html.reviews$.MODULE$, views.html.reviews$.MODULE$.ref());
        assertSerialized(views.html.reviews$.MODULE$);
    }

    @Test
    public void testGlobalDiversityTemplateObjectHelpers() throws Exception {
        String html = views.html.globalDiversity.render("movie", 1, "Test", 0.5, 0.6, request, messages, webJarsUtil).body();
        assertTrue(html.contains("Global Diversity Analysis"));

        assertNotNull(views.html.globalDiversity$.MODULE$.f());
        assertEquals(views.html.globalDiversity$.MODULE$, views.html.globalDiversity$.MODULE$.ref());
        assertSerialized(views.html.globalDiversity$.MODULE$);
    }

    @Test
    public void testFinancialPerformanceTemplateObjectHelpers() throws Exception {
        FinancialPerformance fp = new FinancialPerformance(100_000_000L, 250_000_000L);
        String html = views.html.financialPerformance.render(fp, request, messages, webJarsUtil).body();
        assertTrue(html.contains("Financial Performance"));

        assertNotNull(views.html.financialPerformance$.MODULE$.f());
        assertEquals(views.html.financialPerformance$.MODULE$, views.html.financialPerformance$.MODULE$.ref());
        assertSerialized(views.html.financialPerformance$.MODULE$);
    }

    @Test
    public void testMainTemplateObjectHelpersAndRender() throws Exception {
        // Explicitly call render to cover main$.render line
        String html = views.html.main$.MODULE$.render("Title", play.twirl.api.Html.apply("<p>Body</p>"), request, webJarsUtil).body();
        assertTrue(html.contains("<title>Title</title>"));
        assertTrue(html.contains("Body"));

        assertNotNull(views.html.main$.MODULE$.f());
        assertEquals(views.html.main$.MODULE$, views.html.main$.MODULE$.ref());
        assertSerialized(views.html.main$.MODULE$);
    }

    private void assertSerialized(Object value) throws Exception {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        try (ObjectOutputStream out = new ObjectOutputStream(baos)) {
            out.writeObject(value);
        }
        assertTrue(baos.size() > 0);
    }
}





